### ISSUE TITLE
well, well, well

### ISSUE THREAD

**Issue by Tangent-Wei** [LC1332/Luotuo-Chinese-LLM#16]
![1679908167667](https://user-images.githubusercontent.com/11977882/227896532-16583fb4-b252-492c-ac64-6a9708c84c85.jpg)

**Comment by qiyuan-chen** [comment]
感谢您的关注与测试。目前网页版本的代码是错误的，可能会导致效果较差，性能测试还请使用notebook，同时由于我们的luotuo是基于llama+lora技术训练而来，而llama缺少中文语料的训练，可能会导致它对于中文事实性的问题回答效果较差。可以尝试0.3版本的模型或者期待我们后续1.0版本的模型，会在事实性问题上的表现更好
