### ISSUE TITLE
有没有尝试过GLM做基座

### ISSUE THREAD

**Issue by rayvzn119** [LC1332/Luotuo-Chinese-LLM#33]
LLaMA在中文上表现挺一般的，基于LLaMA的微调项目，我感觉中文能力都很差，根本比不上glm-6b。基于glm6b去微调，中文表现可能会更好一些

**Comment by LC1332** [comment]
麻烦查看主页的驼铃项目，谢谢对我们的关注。

**Comment by xiaozhubenben** [comment]
项目命名太随意 有点搞不清了
