### ISSUE TITLE
[error] 骆驼的colab似乎有问题

### ISSUE THREAD

**Issue by Cool-CoCoder** [LC1332/Luotuo-Chinese-LLM#36]
使用你们提供的代码,input任何信息都会报错.

**Comment by LC1332** [comment]
对的，GLM更新了他的模型和代码，我们要修复一下等我们这波embedding模型训练完就给更新上

**Comment by LC1332** [comment]
我们修复了除了ChatLuotuo以外的所有notebook代码，让我关闭这个issue，保留ChatLuotuo的那个

**Comment by maxadc** [comment]
哦,我还以为是goolge给的免费资源不够
