### ISSUE TITLE
“TuoLingC_evaluation_code.ipynb”报错。我测试了三个都这样，这是什么问题

### ISSUE THREAD

**Issue by maxadc** [LC1332/Luotuo-Chinese-LLM#43]
Put your rich text here which you want to summarize it: 佛挡杀佛水电费
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py:3553 in run_code         │
│                                                                                                  │
│   3550 │   │   │   │   elif async_ :                                                             │
│   3551 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3552 │   │   │   │   else:                                                                     │
│ ❱ 3553 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3554 │   │   │   finally:                                                                      │
│   3555 │   │   │   │   # Reset our crash handler in place                                        │
│   3556 │   │   │   │   sys.excepthook = old_excepthook                                           │
│ in <cell line: 1>:1                                                                              │
│ in evaluate:10                                                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/peft/peft_model.py:716 in generate                        │
│                                                                                                  │
│    713 │   │   self.base_model.prepare_inputs_for_generation = self.prepare_inputs_for_generati  │
│    714 │   │   try:                                                                              │
│    715 │   │   │   if not isinstance(peft_config, PromptLearningConfig):                         │
│ ❱  716 │   │   │   │   outputs = self.base_model.generate(**kwargs)                              │
│    717 │   │   │   else:                                                                         │
│    718 │   │   │   │   if "input_ids" not in kwargs:                                             │
│    719 │   │   │   │   │   raise ValueError("input_ids must be provided for Peft model generati  │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/peft/peft_model.py:716 in generate                        │
│                                                                                                  │
│    713 │   │   self.base_model.prepare_inputs_for_generation = self.prepare_inputs_for_generati  │
│    714 │   │   try:                                                                              │
│    715 │   │   │   if not isinstance(peft_config, PromptLearningConfig):                         │
│ ❱  716 │   │   │   │   outputs = self.base_model.generate(**kwargs)                              │
│    717 │   │   │   else:                                                                         │
│    718 │   │   │   │   if "input_ids" not in kwargs:                                             │
│    719 │   │   │   │   │   raise ValueError("input_ids must be provided for Peft model generati  │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py:115 in decorate_context        │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:1437 in generate         │
│                                                                                                  │
│   1434 │   │   │   │   )                                                                         │
│   1435 │   │   │                                                                                 │
│   1436 │   │   │   # 11. run greedy search                                                       │
│ ❱ 1437 │   │   │   return self.greedy_search(                                                    │
│   1438 │   │   │   │   input_ids,                                                                │
│   1439 │   │   │   │   logits_processor=logits_processor,                                        │
│   1440 │   │   │   │   stopping_criteria=stopping_criteria,                                      │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:2248 in greedy_search    │
│                                                                                                  │
│   2245 │   │   │   model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)  │
│   2246 │   │   │                                                                                 │
│   2247 │   │   │   # forward pass to get next token                                              │
│ ❱ 2248 │   │   │   outputs = self(                                                               │
│   2249 │   │   │   │   **model_inputs,                                                           │
│   2250 │   │   │   │   return_dict=True,                                                         │
│   2251 │   │   │   │   output_attentions=output_attentions,                                      │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:166 in new_forward                    │
│                                                                                                  │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│   165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│ ❱ 166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│   169 │   return module                                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:292 in post_forward                   │
│                                                                                                  │
│   289 │   │   │   │   set_module_tensor_to_device(module, name, "meta")                          │
│   290 │   │                                                                                      │
│   291 │   │   if self.io_same_device and self.input_device is not None:                          │
│ ❱ 292 │   │   │   output = send_to_device(output, self.input_device)                             │
│   293 │   │                                                                                      │
│   294 │   │   return output                                                                      │
│   295                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/utils/operations.py:133 in send_to_device      │
│                                                                                                  │
│   130 │   def _has_to_method(t):                                                                 │
│   131 │   │   return hasattr(t, "to")                                                            │
│   132 │                                                                                          │
│ ❱ 133 │   return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_h   │
│   134                                                                                            │
│   135                                                                                            │
│   136 def get_data_structure(data):                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/utils/operations.py:92 in recursively_apply    │
│                                                                                                  │
│    89 │   │   │   ),                                                                             │
│    90 │   │   )                                                                                  │
│    91 │   elif isinstance(data, Mapping):                                                        │
│ ❱  92 │   │   return type(data)(                                                                 │
│    93 │   │   │   {                                                                              │
│    94 │   │   │   │   k: recursively_apply(                                                      │
│    95 │   │   │   │   │   func, v, *args, test_type=test_type, error_on_other_type=error_on_ot   │
│ in __init__:8                                                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/utils/generic.py:246 in __post_init__        │
│                                                                                                  │
│   243 │   │   first_field = getattr(self, class_fields[0].name)                                  │
│   244 │   │   other_fields_are_none = all(getattr(self, field.name) is None for field in class   │
│   245 │   │                                                                                      │
│ ❱ 246 │   │   if other_fields_are_none and not is_tensor(first_field):                           │
│   247 │   │   │   if isinstance(first_field, dict):                                              │
│   248 │   │   │   │   iterator = first_field.items()                                             │
│   249 │   │   │   │   first_field_iterator = True                                                │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/utils/generic.py:86 in is_tensor             │
│                                                                                                  │
│    83 │   │   if isinstance(x, torch.Tensor):                                                    │
│    84 │   │   │   return True                                                                    │
│    85 │   if is_tf_available():                                                                  │
│ ❱  86 │   │   import tensorflow as tf                                                            │
│    87 │   │                                                                                      │
│    88 │   │   if isinstance(x, tf.Tensor):                                                       │
│    89 │   │   │   return True                                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py:37 in <module>                     │
│                                                                                                  │
│    34 import sys as _sys                                                                         │
│    35 import typing as _typing                                                                   │
│    36                                                                                            │
│ ❱  37 from tensorflow.python.tools import module_util as _module_util                            │
│    38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader                   │
│    39                                                                                            │
│    40 # Make sure code inside the TensorFlow codebase can use tf2.enabled() at import.           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/tensorflow/python/__init__.py:37 in <module>              │
│                                                                                                  │
│    34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top                   │
│    35                                                                                            │
│    36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow                      │
│ ❱  37 from tensorflow.python.eager import context                                                │
│    38                                                                                            │
│    39 # pylint: enable=wildcard-import                                                           │
│    40                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/tensorflow/python/eager/context.py:28 in <module>         │
│                                                                                                  │
│     25 from absl import logging                                                                  │
│     26 import numpy as np                                                                        │
│     27                                                                                           │
│ ❱   28 from tensorflow.core.framework import function_pb2                                        │
│     29 from tensorflow.core.protobuf import config_pb2                                           │
│     30 from tensorflow.core.protobuf import rewriter_config_pb2                                  │
│     31 from tensorflow.python import pywrap_tfe                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/tensorflow/core/framework/function_pb2.py:5 in <module>   │
│                                                                                                  │
│    2 # Generated by the protocol buffer compiler.  DO NOT EDIT!                                  │
│    3 # source: tensorflow/core/framework/function.proto                                          │
│    4 """Generated protocol buffer code."""                                                       │
│ ❱  5 from google.protobuf.internal import builder as _builder                                    │
│    6 from google.protobuf import descriptor as _descriptor                                       │
│    7 from google.protobuf import descriptor_pool as _descriptor_pool                             │
│    8 from google.protobuf import symbol_database as _symbol_database                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'builder' from 'google.protobuf.internal' 
(/usr/local/lib/python3.9/dist-packages/google/protobuf/internal/__init__.py)

**Comment by LC1332** [comment]
我让运维的同学看一看

**Comment by SirlyDreamer** [comment]
已经移除了luotuo-silk-road中对icetk的依赖，该包会强制降级protobuf导致问题，请再试试。
