### ISSUE TITLE
怎么提升效果？

### ISSUE THREAD

**Issue by extrame** [LC1332/Luotuo-Chinese-LLM#44]
我用默认的colab跑了一下骆驼说，似乎效果不佳，是需要升级到colab pro么？还是需要做别的事情？

[生成链接](https://7e9065083f4a60932c.gradio.live/)

```
### Instruction:11份23加起来等于多少

### Response:11加23即24。

### Instruction:11乘以23等于多少

### Response:11乘23=243。

### Instruction:不对，是253

### Response:我错！

### Instruction:11乘以23等于多少

### Response:11乘23=243。
```

**Comment by LC1332** [comment]
@extrame  LLaMA和GLM6B都是相对较小的模型

更合适的方法是去再垂类里面应用。

如果希望模型有更“聪明”的行为，需要将模型进一步升级，比如使用65B的模型

或者我们后面会去尝试vicuna 13B的模型。

这些在我们逐步做完很多的技术路线，并且拥有更多的机器捐赠资源之后，会去进行尝试。

另外，在我的理解中，让语言模型直接去处理数学和科学问题，并不是很明智。也不产生太多可能的价值

当然有很多研究在这方面，研究如何提升语言模型对于科学问题的处理，比如引入CoT等技术。

**Comment by LC1332** [comment]
Close

**Comment by initlifeinc** [comment]
> 在我的理解中，让语言模型直接去处理数学和科学问题，并不是很明智。也不产生太多可能的价值
对于大语言模型这方面没什么概念，看到评论顺手想问个问题，那么你认为语言模型最需要最适合去处理的事哪方面？
