### ISSUE TITLE
说是微软也开源了一个看看怎样

### ISSUE THREAD

**Issue by maxadc** [LC1332/Luotuo-Chinese-LLM#45]
https://github.com/microsoft/DeepSpeed

**Comment by LC1332** [comment]
@maxadc 我看到了 而且这个是支持中文的 我一会儿更新到related work里面去

**Comment by LC1332** [comment]
谢谢你的建议 已经加入related work，不过这个工作应该没开源模型参数和数据、、就是个架构。。那样的话只有阅读代码学习的意义感觉，。。
