### ISSUE TITLE
请问有大模型比较经典的技术报告和研究论文吗

### ISSUE THREAD

**Issue by ninghongbo123** [LC1332/Luotuo-Chinese-LLM#47]
不好意思，我记得在你们的项目看到有些研究论文的介绍，但是返回来找，怎么都找不到了，不知道是我记错了？还是这边有一些其他链接是包含相关的技术报告和研究论文。谢谢！

**Comment by LC1332** [comment]
我们项目链接是有的，另外我的现在paper reading主要在我知乎主页～～～

https://www.zhihu.com/people/cheng-li-47/posts

但是我已经在考虑你说的了！不知道在项目这边加个paper reading是否有意义

**Comment by LC1332** [comment]
@ninghongbo123

**Comment by ninghongbo123** [comment]
个人认为，有一些经典的论文和权威的技术报告，是非常有意义的。
现在相关论文也很多，非学术研究人员不具备快速筛选的能力，只是单纯跑个模型，思想认识也提高不了。
如果有大模型的专业研究人员，能够推荐一些经典的论文，对社区的帮助是非常大的。

**Comment by LC1332** [comment]
@ninghongbo123 根据昨天paper reading的情况 我也考虑增加了一个 链接在主页已经可见了 目前回头再招个小编 我这里很多写文档的任务很重已经有点搞不过来了。
