### ISSUE TITLE
请教大佬一个问题

### ISSUE THREAD

**Issue by ChrisXULC** [LC1332/Luotuo-Chinese-LLM#48]
请问 如果我想在32g显存的服务器加载llama 30b，我能不能先把每个shard做了量化之后再载进来呀，因为直接载模型的话就out of memory了，或者其他有没有什么办法可以做到呀，谢谢

**Comment by LC1332** [comment]
我早上本来想回这个问题-o- llama30b好像没有人这么搞哎 但是vicuna我见过有人这么搞。

**Comment by LC1332** [comment]
llama我好像见过小一个级别的这么搞的。

**Comment by ChrisXULC** [comment]
> 我早上本来想回这个问题-o- llama30b好像没有人这么搞哎 但是vicuna我见过有人这么搞。

好滴 我去看看

**Comment by ChrisXULC** [comment]
> 我早上本来想回这个问题-o- llama30b好像没有人这么搞哎 但是vicuna我见过有人这么搞。

谢谢啦

**Comment by LC1332** [comment]
OK 让我关掉这个issue。
