### ISSUE TITLE
llama + alpaca + lora不收敛

### ISSUE THREAD

**Issue by SiriusWy** [LC1332/Luotuo-Chinese-LLM#49]
你好，我在训练过程中，模型无法学习到自定义数据，lora模型的训练也不收敛，loss一直1.0左右，请问这个遇到过吗？

**Comment by LC1332** [comment]
我们以前有个赞助人语料是多射的时候也不收敛，这个和语料关系是有的。另外你把ranking调高 先看看会不会overfitting。

**Comment by LC1332** [comment]
let me close the issue
