### ISSUE TITLE
trans_chinese_alpaca_data.json下载后为什么只有1行？

### ISSUE THREAD

**Issue by NewEricWang** [LC1332/Luotuo-Chinese-LLM#58]
命令如下：wget https://github.com/LC1332/Chinese-alpaca-lora/blob/main/data/trans_chinese_alpaca_data.json

**Comment by LC1332** [comment]
我看那个文件挺大的。。应该是有很多内容吧-o- 会不会是json被当作jsonl解析了

**Comment by NewEricWang** [comment]
谢谢！好象是源的问题或者服务器问题，现在可以了！
